In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = pd.read_csv('/content/movies_metadata.csv')

/tmp/ipykernel_6516/656377271.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('/content/movies_metadata.csv')

In [ ]:
data.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [ ]:
data.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [ ]:
data.shape

(45466, 24)

In [ ]:
data.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [ ]:
data = data.drop_duplicates().reset_index(drop = True)

In [ ]:
data['genres'][0]

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [ ]:
for i in data['genres'][1:3]:
  print(i)

[{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 10751, 'name': 'Family'}]
[{'id': 10749, 'name': 'Romance'}, {'id': 35, 'name': 'Comedy'}]

In [ ]:
data = data[['id','title','overview','genres','tagline','vote_average','popularity']]

In [ ]:
data.head()

,id,title,overview,genres,tagline,vote_average,popularity
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,7.7,21.946943
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,6.9,17.015539
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,6.1,3.859495
4,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [ ]:
data.isnull().sum()

id                  0
title               6
overview          954
genres              0
tagline         25045
vote_average        6
popularity          5
dtype: int64

In [ ]:
data = data.dropna(subset = ['title'])

In [ ]:
data.isnull().sum()

id                  0
title               0
overview          954
genres              0
tagline         25039
vote_average        0
popularity          0
dtype: int64

In [ ]:
data.shape

(45447, 7)

In [ ]:
data['overview'] = data['overview'].fillna('')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45447 entries, 0 to 45452
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            45447 non-null  object
 1   title         45447 non-null  object
 2   overview      45447 non-null  object
 3   genres        45447 non-null  object
 4   tagline       20408 non-null  object
 5   vote_average  45447 non-null  float64
 6   popularity    45447 non-null  object
dtypes: float64(1), object(6)
memory usage: 2.8+ MB

In [ ]:
import ast
for i in ast.literal_eval(data['genres'][0]):

    print(i['name'])

Animation
Comedy
Family

In [ ]:
def genre(genres):
  genress = []
  for i in ast.literal_eval(genres):
    genress.append(i['name'])
  return " ".join(genress)

In [ ]:
data['genres'] = data['genres'].apply(genre)

In [ ]:
data.head()

,id,title,overview,genres,tagline,vote_average,popularity
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,NaN,7.7,21.946943
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495
4,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [ ]:
data['tagline'] = data['tagline'].fillna('')

In [ ]:
data.isnull().sum()

id              0
title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [ ]:
data['tags'] = data['overview'] + " " + data['genres'] + " " + data['tagline']

In [ ]:
data.head()

,id,title,overview,genres,tagline,vote_average,popularity,tags
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,A family wedding reignites the ancient feud be...
3,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

In [ ]:
data['tags'][0]

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences. Animation Comedy Family "

In [ ]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [ ]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
stop_words = set(stopwords.words('english'))
def remove_stopwords(text):
  new_text = []
  for i in text.split():
    if i not in stop_words:
      new_text.append(i)
  return " ".join(new_text)

In [ ]:
remove_stopwords(data['tags'][0])

"Led Woody, Andy's toys live happily room Andy's birthday brings Buzz Lightyear onto scene. Afraid losing place Andy's heart, Woody plots Buzz. But circumstances separate Buzz Woody owner, duo eventually learns put aside differences. Animation Comedy Family"

In [ ]:
lemmatizer = WordNetLemmatizer()
def preprocess(text):
  text = str(text).lower()

  text = re.sub(r'[^a-zA-Z\s]','', text)

  words = text.split();
  words = [word for word in words if word not in stop_words]

  words = [lemmatizer.lemmatize(word) for word in words]

  return " ".join(words)

In [ ]:
preprocess(data['tags'][0])

'led woody andys toy live happily room andys birthday brings buzz lightyear onto scene afraid losing place andys heart woody plot buzz circumstance separate buzz woody owner duo eventually learns put aside difference animation comedy family'

In [ ]:
data['tags'] = data['tags'].apply(preprocess)

In [ ]:
data = data.reset_index(drop = True)

In [ ]:
indices = pd.Series(data.index, index = data['title']).drop_duplicates()
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features = 50000, ngram_range=(1,2))

In [ ]:
tfidf_matrix = tfidf.fit_transform(data['tags'])

In [ ]:
tfidf_matrix.shape

(45447, 50000)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
top = sorted(list(enumerate(cosine_similarity(tfidf_matrix[0],tfidf_matrix).ravel())),key = lambda x:x[1], reverse = True)[1:11]

In [ ]:
top[0][0]

2996

In [ ]:
indices.index[2996]

'Toy Story 2'

In [ ]:
for i in top:
  movie = i[0]
  print(indices.index[movie])

Toy Story 2
Toy Story 3
Small Fry
Superstar Goofy
What's Up, Tiger Lily?
Group Sex
For Your Consideration
Rebel Without a Cause
The Wild
Condorman

In [ ]:
def recommend(movie):
  if movie not in indices.index:
    return "Movie not found"
  movie_index = indices[movie]
  top_10 = sorted(list(enumerate(cosine_similarity(tfidf_matrix[movie_index],tfidf_matrix).ravel())),key = lambda x:x[1], reverse = True)[1:11]
  for i in top_10:
    movies = i[0]
    print(indices.index[movies])

In [ ]:
recommend('Toy Story 2')

Toy Story 3
Toy Reanimator
How the Toys Saved Christmas
The Mouse and His Child
Toy Story
Silent Night, Deadly Night 5: The Toy Maker
Dollman vs. Demonic Toys
Toy Story of Terror!
Plastic Galaxy: The Story of Star Wars Toys
Dolly Dearest